---
- name: Bring up EC2 instances, security groups
  hosts: all 
  connection: local
  vars_files:
    - vars/credentials.yml
    - defaults/main.yml
  roles:
    - ec2-dynamic-inventory
  environment:
    ANSIBLE_HOST_KEY_CHECKING: False

- name: Bring up ELB and attach instances to it
  hosts: launched
  gather_facts: False
  vars_files:
    - vars/credentials.yml
    - defaults/main.yml

  roles:
    - ec2-loadbalancers

- name: Install elasticsearch, logstash and kibana
  hosts: launched
  become: True
  vars_files:
    - vars/credentials.yml
    - defaults/main.yml

  roles:
    - ansible-role-java
    - { role: ansible-role-elasticsearch, when: "'elasticsearch' in hostvars[inventory_hostname].type" }
    - { role: ansible-role-logstash, when: "'logstash' in hostvars[inventory_hostname].type " }
    - { role: ansible-role-kibana, when: "'kibana' in hostvars[inventory_hostname].type" }


