---
# tasks file for elasticsearch
- name: create security group
  ec2_group:
    name: sg_elasticsearch
    description: rule for elasticsearch
    rules:
    - proto: tcp
      ports:
      - 80
      - 22
      - 9200
      cidr_ip: 0.0.0.0/0
      rule_desc: allow ssh, http and es

- name: boot ec2 instance
  ec2:
    count: 3
    key_name: "{{ key_name }}"
    region: "{{ region }}"
    instance_type: t2.micro
    image: "{{ ami_id }}"
    wait: yes
    group: sg_elasticsearch
    vpc_subnet_id: "{{ vpc_subnet_id }}"
    assign_public_ip: yes
    state: present
    instance_tags:
      type: elasticsearch
      env: dev
  register: ec2

- name: Add new instance to a host group
  add_host:
    hostname: "{{ item.public_ip }}"
    groupname: launched
  with_items: "{{ ec2.instances }}" 
